name: Build & Publish Docker image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Custom image tag (default: commit SHA)"
        required: false
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Compute image version
        id: version
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "value=${{ github.event.inputs.image_tag || github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT  # strip refs/tags/
          fi

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qwen-bnb4:latest
            ghcr.io/${{ github.repository_owner }}/qwen-bnb4:${{ github.sha }}
